### ISSUE TITLE
Rotation problem

### ISSUE THREAD

**Issue by rawmean** [MarioIannotta/MIPivotPageController#7]
the view controllers do not resize correctly when auto-rotate is enabled. Can't figure out how to fix it.  Any help is appreciated.  This is a great controller.

**Comment by MarioIannotta** [comment]
Hi,
I've fixed this issue with this [commit](https://github.com/MarioIannotta/MIPivotPageController/commit/292ec75f3ca65fa04cc5e67848a35f2965b094e3).

Have a nice day,
Mario.

**Comment by rawmean** [comment]
Thanks for the quick response. I updated to the latest version but the auto-rotate problem still exists.
You can also reproduce this problem in your demo code. Choose iPad in the simulator and navigate to your third tab and then rotate the simulator.

Here is a screenshot video:
https://www.dropbox.com/s/ysvmt3xcxo4zme7/autorotate.mov?dl=0
